YAML

name: Basic CI

on:
push:
branches: [ main ]
pull_request:
branches: [ main ]

jobs:
test:
run-on: ubuntu-latest

steps:
- name:: checkout code
user: actions/checkout@v4

-name:Run test
run: echo "CI Pipeline is working!"
